[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  external_node_modules = [
    "@nestjs/core",
    "@nestjs/microservices",
    "@nestjs/websockets",
    "@nestjs/platform-socket.io",
    "@grpc/grpc-js",
    "@grpc/proto-loader",
    "nats",
    "ioredis",
    "amqplib",
    "kafkajs",
    "mqtt"
  ]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
